noun_sg(person, person, neutr).
noun_pl(persons, person, neutr).
noun_sg(human-being, human-being, neutr).
adj_tr('parent-of', 'parent-of', of).
adj_tr('child-of', 'child-of', of).
noun_sg(common-noun, common-noun, neutr).
noun_sg(simple-noun, simple-noun, neutr).
noun_sg(noun, noun, neutr).
noun_sg(college, college, neutr).
noun_pl(colleges, college, neutr).
noun_sg(university, university, neutr).
noun_sg(human, human, neutr).
noun_sg(people, people, neutr).
pn_sg('Ananya', 'Ananya', neutr).
pn_sg('Shruti', 'Shruti', neutr).
pn_sg('User', 'User', neutr).
pn_sg('Sancheeta', 'Sancheeta', neutr).
pn_sg('Crunch', 'Crunch', neutr).
adj_tr('located-in', 'located-in', in).
prep(in, in).
tv_finsg(contains, contain).
adj_tr('spouse-of', 'spouse-of', of).
prep(of, of).
adj_tr('sibling-of', 'sibling-of', of).
adj_tr('friend-of', 'friend-of', of).
noun_sg(time, time, neutr).
noun_sg(date, date, neutr).
noun_sg(color, color, neutr).
noun_sg(date-of-birth, date-of-birth, neutr).
noun_sg(birth-date, birth-date, neutr).
tv_finsg(comprises, comprise).
pn_sg('India', 'India', neutr).
pn_sg('Bharat', 'Bharat', neutr).
pn_sg('Mumbai', 'Mumbai', neutr).
pn_sg('Bombay', 'Bombay', neutr).
noun_sg(place, place, neutr).
noun_pl(places, place, neutr).
noun_sg(location, location, neutr).
noun_sg(man, man, neutr).
noun_pl(men, man, neutr).
noun_sg(male, male, neutr).
pn_sg('Delhi', 'Delhi', neutr).
pn_sg('Sugu', 'Sugu', neutr).
noun_sg(proper-noun, proper-noun, neutr).
noun_sg(population, population, neutr).
noun_sg(laboratory, laboratory, neutr).
noun_pl(laboratories, laboratory, neutr).
noun_sg(lab, lab, neutr).
noun_sg(field, field, neutr).
noun_sg(profession, profession, neutr).
noun_pl(professions, profession, neutr).
noun_sg(career, career, neutr).
noun_sg(teacher, teacher, neutr).
noun_pl(teachers, teacher, neutr).
noun_sg(professor, professor, neutr).
noun_pl(universities, university, neutr).
noun_sg(country, country, neutr).
noun_pl(countries, country, neutr).
noun_sg(nation, nation, neutr).
noun_sg(city, city, neutr).
noun_pl(cities, city, neutr).
noun_sg(metropolis, metropolis, neutr).
noun_sg(institution, institution, neutr).
pn_sg('Milind-K', 'Milind-K', neutr).
pn_sg('Engineering', 'Engineering', neutr).
pn_sg('Computer-Science', 'Computer-Science', neutr).
pn_sg('Information-Technology', 'Information-Technology', neutr).
pn_sg('It', 'It', neutr).
pn_sg('Vidyullata-Devmane', 'Vidyullata-Devmane', neutr).
pn_sg('Abirami-Shivaprasad', 'Abirami-Shivaprasad', neutr).
pn_sg('Mumbai-University', 'Mumbai-University', neutr).
pn_sg('Shah-And-Anchor-Kutchhi-Engineering-College', 'Shah-And-Anchor-Kutchhi-Engineering-College', neutr).
pn_sg('Sakec', 'Sakec', neutr).
pn_sg('Vinit-Kotak', 'Vinit-Kotak', neutr).
pn_sg('Kotak-Sir', 'Kotak-Sir', neutr).
tv_finsg(teaches, teach).
noun_sg(taught, taught, neutr).
noun_pl(taughts, taught, neutr).
adj_tr('taught-by', 'taught-by', by).
prep(by, by).
noun_sg(student, student, neutr).
noun_pl(students, student, neutr).
adj_tr('student-of', 'student-of', of).
noun_sg(teacher, teacher, neutr).
noun_pl(teachers, teacher, neutr).
adj_tr('teacher-of', 'teacher-of', of).
noun_sg(branch, branch, neutr).
noun_pl(branches, branch, neutr).
adj_tr('branch-of', 'branch-of', of).
noun_sg(comprises, comprises, neutr).
noun_pl(comprise, comprises, neutr).
adj_tr('comprises-of', 'comprises-of', of).
noun_sg(bigger, bigger, neutr).
noun_pl(biggers, bigger, neutr).
adj_tr('bigger-than', 'bigger-than', than).
prep(than, than).
noun_sg(smaller, smaller, neutr).
noun_pl(smallers, smaller, neutr).
adj_tr('smaller-than', 'smaller-than', than).
noun_sg(located, located, neutr).
noun_pl(locateds, located, neutr).
noun_sg(spouse, spouse, neutr).
noun_pl(spouses, spouse, neutr).
noun_sg(sibling, sibling, neutr).
noun_pl(siblings, sibling, neutr).
noun_sg(friend, friend, neutr).
noun_pl(friends, friend, neutr).
noun_sg(parent, parent, neutr).
noun_pl(parents, parent, neutr).
noun_sg(child, child, neutr).
noun_pl(children, child, neutr).
adj_tr('husband-of', 'husband-of', of).
adj_tr('wife-of', 'wife-of', of).
adj_tr('trunk-of', 'trunk-of', of).
